// <auto-generated>
// Generated by tools/generate-store-ids/generate.mjs from the `Store` seed
// in V.SMART/V.SMART.Shared/Data/ApplicationDbContext.cs. Do not edit by
// hand -- if this file is wrong, fix the generator and regenerate:
//
//   node tools/generate-store-ids/generate.mjs
//
// See docs/kb/execution/tasks/M2-B05.md and
// docs/kb/risks/technical-debt-register.md (R-66) for why this exists.
// </auto-generated>
namespace V.SMART.Shared.Utility_Constants
{
    public static class StoreIds
    {
        public const int MainStore          = 1;    // "MAIN STORE"
        public const int PurchaseStore      = 2;    // "PURCHASE STORE"
        public const int SubContractStore   = 3;    // "SUB-CONTRACT STORE"
        public const int LabourStore        = 4;    // "LABOUR STORE"
        public const int ProductionStore    = 5;    // "PRODUCTION STORE"
        public const int RejectionStore     = 6;    // "REJECTION STORE"
        public const int ReworkStore        = 7;    // "REWORK STORE"
        public const int FinishGoodsFgStore = 8;    // "FINISH GOODS (FG) STORE"
        public const int RoutecardStore     = 9;    // "ROUTECARD STORE"

        public static readonly System.Collections.Generic.IReadOnlyDictionary<int, string> Names =
            new System.Collections.Generic.Dictionary<int, string>
            {
            { 1, "MAIN STORE" },
            { 2, "PURCHASE STORE" },
            { 3, "SUB-CONTRACT STORE" },
            { 4, "LABOUR STORE" },
            { 5, "PRODUCTION STORE" },
            { 6, "REJECTION STORE" },
            { 7, "REWORK STORE" },
            { 8, "FINISH GOODS (FG) STORE" },
            { 9, "ROUTECARD STORE" },
            };
    }
}
