namespace V.SMART.Api.Authorization
{
    /// <summary>
    /// A compile-time copy of the 152 seeded <c>Screens.ScreenName</c> values (KB-105 §2.7,
    /// Appendix A).
    /// <para>
    /// Used <b>only</b> by <see cref="ScreenRightStartupValidator"/> (KB-105 D-6). It is never
    /// consulted at request time: the authorization decision always comes from the tenant
    /// database, never from this list.
    /// </para>
    /// <para>
    /// Validating against the compiled catalogue rather than the database is forced, not chosen —
    /// <c>Screens</c> lives in the tenant database, which is resolved per request from the JWT
    /// (<c>TenantProvider.cs:33-44</c>), so there is no tenant context at startup and there may be
    /// many tenants. Throwing on an unseeded name is safe because no code path writes a
    /// <c>Screens</c> row (KB-105 §1.3, Confirmed negative result).
    /// </para>
    /// <para>
    /// Extracted programmatically from
    /// <c>V.SMART/V.SMART.Shared/Data/ApplicationDbContext.cs</c> starting at the
    /// <c>builder.Entity&lt;Screens&gt;().HasData(</c> seed, not transcribed by hand. The seed's
    /// own misspellings are canonical and must not be "corrected" (KB-105 F-8:
    /// <c>"Sub-Contrect GRN"</c>, <c>"Advaceadjustment"</c>). M2-B05 replaces this hand-copied set
    /// with a generated one (R-10); until then this type and Appendix A are updated together or
    /// not at all.
    /// </para>
    /// </summary>
    public static class ScreenCatalogue
    {
        /// <summary>The 152 seeded <c>ScreenName</c> values. Ordinal set.</summary>
        public static IReadOnlySet<string> SeededScreenNames { get; } = new HashSet<string>(StringComparer.Ordinal)
        {
            "User",
            "Category",
            "UOM",
            "State",
            "Currency",
            "User Rights",
            "Store",
            "Raw Material",
            "Factors",
            "Process",
            "Machine",
            "Grouping",
            "Item",
            "HSN Master",
            "Customer",
            "Expense",
            "Screen Management",
            "Vendor",
            "BOM",
            "Income",
            "Currency Today",
            "Bank",
            "Company",
            "Correspondences",
            "Master Upload",
            "Holiday List",
            "Staff",
            "LeaveType",
            "Employee Leave Balance",
            "Leave Application",
            "Project Type Master",
            "Cost-Center",
            "User Level Authorization",
            "Shift Allocation",
            "Item Rate-Updation",
            "Manufacturing Quotation",
            "Terms and Conditions",
            "Leads",
            "Enquiry Sales",
            "Authorization",
            "Sales Order",
            "Manufacturing DC",
            "General Settings",
            "Store Map",
            "Performa Invoice",
            "Stock-Add",
            "Material Requisition",
            "Material Issue-Note",
            "Enquiry Purchase",
            "Material Requirement Analysis",
            "Print Management",
            "Enquiry Feasibility",
            "Job Order",
            "Production Issue WO Assembly",
            "Production Return GRN Assembly",
            "Production SCN Assembly",
            "Tool-Crib Issue",
            "Tool-Crib Return",
            "Instant Search",
            "Route Card",
            "Production Log Setting",
            "Daily Production Log",
            "Process Flow-RC",
            "MaintenanceSchedule",
            "MaintenanceProcess",
            "BreakdownMaintenance",
            "CalibrationHistoryAndMaintenance",
            "Production Issue WO Component",
            "Inter Store Transfer",
            "Production Return Component",
            "Production SCN Component",
            "Contract Review",
            "Contract Review CheckList",
            "Stock Position",
            "Purchase-Quotation",
            "Purchase Order",
            "Purchase GRN",
            "Purchase SCN",
            "Purchase Invoice",
            "Manufacturing Invoice",
            "Sub-Contract DC-Out",
            "Sub-Contrect GRN",
            "Sub-Contract SCN",
            "Sub-Contract Invoice",
            "Export Invoice",
            "MasterInspection",
            "FinalInspection",
            "IncomingInspection",
            "InspectionSettings",
            "DefectInfo",
            "Assembly Requirement Analysis",
            "Labour GRN",
            "Labour SCN",
            "Labour Delivery Challan",
            "Labour Invoice",
            "Route Card Release",
            "Excel Upload",
            "Credit Note",
            "Printing Map",
            "LabourCostManagement",
            "BOMLabourCost",
            "Sales Track Report",
            "Debit Note",
            "Tags",
            "Labour Track Report",
            "Payments",
            "Advaceadjustment",
            "Receipts",
            "Fundtransactions",
            "Dashboard",
            "Stock Ledger",
            "Stock Analysis",
            "ViewTallyDc-In-Out",
            "Bill Pending List",
            "Bill Paid List",
            "Service Bills",
            "Po Pendings",
            "Pending Statements",
            "ToolCribIssue Summary",
            "ItemHistory",
            "Confirmation Of Accounts",
            "Stock Position(Internal & External)",
            "TaxDetails Report",
            "Profit & Loss Accounts",
            "Item Modification",
            "RejectionMaster",
            "Day Book",
            "Labour Pending",
            "View Po Track",
            "Production Pending Summary",
            "Rejection Analysis",
            "GSTITC04",
            "HRMaster",
            "Biometric Excel Set",
            "Salary Head Print Setting",
            "Salary",
            "Attendance",
            "StaffLoan",
            "BOM Labour",
            "Ratings",
            "Purchase Sales Track",
            "Estimation",
            "Route Card Analysis",
            "Stock Issue-Request",
            "CreditDebit Summary Report",
            "TDSummary Report",
            "HSNSummary Report",
            "PR PO Rating Report",
            "Candidate",
            "Offer Letter",
            "Appointment Letter",
            "Joborder Track",
        };
    }
}
