CREATE OR ALTER PROCEDURE Sp_Print_CompanyDetails
AS
BEGIN
    SELECT 
        CAST(CD.CompanyName AS NVARCHAR(150)) AS CompanyName,
        CAST(CD.RegisteredAddress AS NVARCHAR(300)) AS RegisteredAddress,
        CAST(CD.BillingAddress AS NVARCHAR(300)) AS BillingAddress,
        CAST(CD.ShippingAddress AS NVARCHAR(300)) AS ShippingAddress,
        CAST(CD.City AS NVARCHAR(100)) AS City,
        CAST(CD.StateName AS NVARCHAR(100)) AS StateName,
        CAST(CD.Country AS NVARCHAR(100)) AS Country,
        CAST(CD.ZipCode AS NVARCHAR(10)) AS ZipCode,
        CAST(CD.PhoneNumber AS NVARCHAR(20)) AS PhoneNumber,
        CAST(CD.MobileNumber AS NVARCHAR(15)) AS MobileNumber,
        CAST(CD.EmailId AS NVARCHAR(100)) AS EmailId,
        CAST(CD.Website AS NVARCHAR(100)) AS Website,
        CAST(CD.GSTIN AS NVARCHAR(15)) AS GSTIN,
        CAST(CD.PAN AS NVARCHAR(10)) AS PAN,
        CAST(CD.IECNumber AS NVARCHAR(30)) AS IECNumber,
        CD.IsEOURegistered,
        CAST(CD.LUTNumber AS NVARCHAR(50)) AS LUTNumber,
        CAST(CD.BankAuthorizedDealerCode AS NVARCHAR(30)) AS BankAuthorizedDealerCode,
        CAST(CD.EOURegistrationNo AS NVARCHAR(50)) AS EOURegistrationNo,
        CD.EOURegistrationDate,
        CAST(CD.EOUStatus AS NVARCHAR(20)) AS EOUStatus,
        CD.EOUValidityTill,
        CAST(CD.FinancialYearType AS NVARCHAR(20)) AS FinancialYearType,
        CD.OpeningBalance,
        CD.OpeningBalanceDate,
        CAST(CD.LogoPath AS NVARCHAR(200)) AS LogoPath,
        CAST(CD.LogoUrl AS NVARCHAR(200)) AS LogoUrl,
        CAST(CD.IsoLogoPath AS NVARCHAR(200)) AS IsoLogoPath,
        CAST(CD.IsoLogoUrl AS NVARCHAR(200)) AS IsoLogoUrl,
        CD.CurrencyCode,
        CAST(CD.TimeZone AS NVARCHAR(100)) AS TimeZone,
        CAST(CD.CIN AS NVARCHAR(21)) AS CIN,
        CAST(CD.TIN AS NVARCHAR(15)) AS TIN,
        CAST(CD.BankName AS NVARCHAR(100)) AS BankName,
        CAST(CD.BankBranch AS NVARCHAR(100)) AS BankBranch,
        CAST(CD.BankAccountNumber AS NVARCHAR(20)) AS BankAccountNumber,
        CAST(CD.BankAddress AS NVARCHAR(300)) AS BankAddress,
        CAST(CD.BankCity AS NVARCHAR(100)) AS BankCity,
        CAST(CD.BankState AS NVARCHAR(100)) AS BankState,
        CAST(CD.AccountType AS NVARCHAR(20)) AS AccountType,
        CAST(CD.IFSCCode AS NVARCHAR(11)) AS IFSCCode,
        CAST(CD.MICRCode AS NVARCHAR(9)) AS MICRCode,
        CAST(CD.SWIFTCode AS NVARCHAR(100)) AS SWIFTCode,
        CAST(CD.UdyamNumber AS NVARCHAR(30)) AS UdyamNumber,
        CAST(CD.PFRegistrationNumber AS NVARCHAR(25)) AS PFRegistrationNumber,
        CAST(CD.ESIRegistrationNumber AS NVARCHAR(25)) AS ESIRegistrationNumber,
        CAST(CD.ShopEstablishmentNumber AS NVARCHAR(30)) AS ShopEstablishmentNumber,
        CAST(CD.ExciseRegistrationNumber AS NVARCHAR(30)) AS ExciseRegistrationNumber,
        CAST(CD.SEZRegistrationNumber AS NVARCHAR(30)) AS SEZRegistrationNumber,
        CAST(CD.CustomsRegistrationNumber AS NVARCHAR(30)) AS CustomsRegistrationNumber,
        CAST(CD.AlternateEmail AS NVARCHAR(100)) AS AlternateEmail,
        CAST(CD.ContactPersonName AS NVARCHAR(100)) AS ContactPersonName,
        CAST(CD.CustomFinancialYearType AS NVARCHAR(20)) AS CustomFinancialYearType,
        CAST(CD.CustomBusinessType AS NVARCHAR(100)) AS CustomBusinessType,
        CAST(CD.CustomIndustryType AS NVARCHAR(100)) AS CustomIndustryType,
        CD.IsActive,
        CD.DecimalPlaces,
        CAST(CD.CreatedBy AS NVARCHAR(100)) AS CreatedBy,
        CD.CreatedDate,
        CAST(CD.ModifiedBy AS NVARCHAR(100)) AS ModifiedBy,
        CD.ModifiedDate
    FROM CompanyDetails CD
END